In [23]:
import numpy as np
from scipy.stats import uniform,randint
from sklearn.datasets import load_breast_cancer,load_diabetes,load_wine
from sklearn.metrics import confusion_matrix,accuracy_score,mean_squared_error
from sklearn.model_selection import cross_val_score,GridSearchCV,KFold,RandomizedSearchCV,train_test_split
import xgboost as xgb

In [3]:
!pip install xgboost

Defaulting to user installation because normal site-packages is not writeable


In [5]:
def display_scores(scores):
    print("Scores:{0}\nmean: {1:.3f}\nstd : {2:.3f}".format(scores,np.mean(scores),np.std(scores)))

In [6]:
diabetes=load_diabetes()

In [8]:
X=diabetes.data
y=diabetes.target
xgb_model=xgb.XGBRegressor(objective='reg:squarederror',random_state=10)

In [9]:
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=10)

In [13]:
xgb_model.fit(X_train,y_train)

XGBRegressor(base_score=0.5, booster='gbtree', callbacks=None,
             colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
             early_stopping_rounds=None, enable_categorical=False,
             eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
             importance_type=None, interaction_constraints='',
             learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
             max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
             missing=nan, monotone_constraints='()', n_estimators=100, n_jobs=0,
             num_parallel_tree=1, predictor='auto', random_state=10,
             reg_alpha=0, reg_lambda=1, ...)

In [16]:
predict=xgb_model.predict(X_test)

In [15]:
xgb_model

XGBRegressor(base_score=0.5, booster='gbtree', callbacks=None,
             colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
             early_stopping_rounds=None, enable_categorical=False,
             eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
             importance_type=None, interaction_constraints='',
             learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
             max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
             missing=nan, monotone_constraints='()', n_estimators=100, n_jobs=0,
             num_parallel_tree=1, predictor='auto', random_state=10,
             reg_alpha=0, reg_lambda=1, ...)

In [19]:
mse=mean_squared_error(predict,y_test)
mse
print('RMSE: ',np.sqrt(mse))

RMSE:  62.664989468847764


In [22]:

print(X[:5]) 
print(y[:5])



[[ 0.03807591  0.05068012  0.06169621  0.02187235 -0.0442235  -0.03482076
  -0.04340085 -0.00259226  0.01990842 -0.01764613]
 [-0.00188202 -0.04464164 -0.05147406 -0.02632783 -0.00844872 -0.01916334
   0.07441156 -0.03949338 -0.06832974 -0.09220405]
 [ 0.08529891  0.05068012  0.04445121 -0.00567061 -0.04559945 -0.03419447
  -0.03235593 -0.00259226  0.00286377 -0.02593034]
 [-0.08906294 -0.04464164 -0.01159501 -0.03665645  0.01219057  0.02499059
  -0.03603757  0.03430886  0.02269202 -0.00936191]
 [ 0.00538306 -0.04464164 -0.03638469  0.02187235  0.00393485  0.01559614
   0.00814208 -0.00259226 -0.03199144 -0.04664087]]
[151.  75. 141. 206. 135.]


In [24]:
cancer=load_breast_cancer()
X=cancer.data
y=cancer.target

In [29]:
xgb_model_2=xgb.XGBClassifier(objective="binary:logistic", random_state=42)
#objective="binary:logistic" tell the Classifier to use logistic Regression for classification
#objective='reg:logistic'use it when the target variable is not discrete
# objective="binary:logistic" tell the Classifier to use logistic Regression for classification
## other objective="reg:logistics" -> classification
## objective="binary:logistic"  --> use it when the target variable is discrete or binary
## objective="reg:logistics"  --> use it when the target variable is not disc

X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=42)
xgb_model_2.fit(X_train,y_train)
predict_y=xgb_model_2.predict(X_test)
print(confusion_matrix(predict_y,y_test))
print(accuracy_score(predict_y,y_test))

[[51  2]
 [ 3 87]]
0.965034965034965


In [30]:
wine=load_wine()

In [31]:
X=wine.data
y=wine.target

In [36]:
import xgboost as xgb
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=42)
xgb_model_3=xgb.XGBClassifier(objective='multi:softprob',random_state=42)
xgb_model_3.fit(X_train,y_train)
pred=xgb_model_3.predict(X_test)
print(accuracy_score(pred,y_test))
print(confusion_matrix(pred,y_test))
from sklearn.metrics import classification_report
print(classification_report(pred,y_test))

0.9333333333333333
[[15  2  0]
 [ 0 16  1]
 [ 0  0 11]]
              precision    recall  f1-score   support

           0       1.00      0.88      0.94        17
           1       0.89      0.94      0.91        17
           2       0.92      1.00      0.96        11

    accuracy                           0.93        45
   macro avg       0.94      0.94      0.94        45
weighted avg       0.94      0.93      0.93        45



In [37]:
X=diabetes.data
y=diabetes.target

In [38]:
kfold=KFold(n_splits=5,shuffle=True,random_state=42)
scores=[]
for train_index,test_index in kfold.split(X):
    X_train,X_test=X[train_index],X[test_index]
    y_train,y_test=y[train_index],y[test_index]
    xgb_model=xgb.XGBRegressor(objective='reg:squarederror')
    xgb_model.fit(X_train,y_train)
    y_pred=xgb_model.predict(X_test)
    scores.append(mean_squared_error(y_test,y_pred))
display_scores(np.sqrt(scores))

Scores:[63.94113133 61.42459265 67.48347385 69.49735119 59.90352074]
mean: 64.450
std : 3.599


array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990842, -0.01764613],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286377, -0.02593034],
       [-0.08906294, -0.04464164, -0.01159501, ...,  0.03430886,
         0.02269202, -0.00936191],
       ...,
       [ 0.04170844,  0.05068012,  0.01966154, ..., -0.00259226,
         0.03119299,  0.00720652],
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04687948,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452837, -0.02593034]])

In [42]:
X=cancer.data
y=cancer.target

In [46]:
xgb_model=xgb.XGBClassifier(objective='binary:logistic',random_state=10,eval_metric='error',n_estimator=150)
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=10)
xgb_model.fit(X_train,y_train,early_stopping_rounds=15,eval_set=[(X_test,y_test)])
y_pred=xgb_model.predict(X_test)
accuracy_score(y_pred,y_test)
## Code Example 5 : Use XGBClassifier with Parameters.
## This could save time for training and give better performance too.            
# n_estimators => the number of boosted trees to train 
# early_stopping_rounds => training continues until validation has not improved in n rounds. 
# eval_set=[(X_test, y_test)] => indicates what parameters to evaluate
# eval_metric="error"  => indicates on what metric to take decision
#              error => Binary classification error rate. It is calculated as #(wrong cases)/#(all cases)
# so if we keep n_estimators = 150 (default is 100) and early_stopping_rounds = 15 then 
# if for 15 runs if our metric say accuracy_score stops improving then the XGBoost model 
# stop
print("best score: {0}, best iteration: {1}, best ntree limit {2}".format(xgb_model.best_score, xgb_model.best_iteration, xgb_model.best_ntree_limit))
best_estimator=xgb_model.best_ntree_limit
xgb_model = xgb.XGBClassifier(objective="binary:logistic", random_state=10, eval_metric="error", n_estimators=best_estimator) 

xgb_model.fit(X_train, y_train, eval_set=[(X_test, y_test)])

y_pred = xgb_model.predict(X_test)

print("-------------- accuracy_score is ----------------")
accuracy_score(y_test, y_pred)

[09:36:25] WARNING: C:/Users/administrator/workspace/xgboost-win64_release_1.6.0/src/learner.cc:627: 
Parameters: { "n_estimator" } might not be used.

  This could be a false alarm, with some parameters getting used by language bindings but
  then being mistakenly passed down to XGBoost core, or some parameter actually being used
  but getting flagged wrongly here. Please open an issue if you find any such cases.


[0]	validation_0-error:0.05594
[1]	validation_0-error:0.06294
[2]	validation_0-error:0.04895
[3]	validation_0-error:0.04196
[4]	validation_0-error:0.04196
[5]	validation_0-error:0.03497
[6]	validation_0-error:0.04196
[7]	validation_0-error:0.04196
[8]	validation_0-error:0.03497
[9]	validation_0-error:0.02797
[10]	validation_0-error:0.02797
[11]	validation_0-error:0.02797
[12]	validation_0-error:0.02098
[13]	validation_0-error:0.02797
[14]	validation_0-error:0.02797
[15]	validation_0-error:0.02797
[16]	validation_0-error:0.02797
[17]	validation_0-error:0.02797
[18]	validatio

C:\Users\RajeshS\AppData\Roaming\Python\Python39\site-packages\xgboost\sklearn.py:793: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(


0.9790209790209791