In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import datasets
%matplotlib inline

In [3]:
iris_data=sns.load_dataset('iris')

In [4]:
iris_data.sample(5)

sepal_length  sepal_width  petal_length  petal_width     species
106           4.9          2.5           4.5          1.7   virginica
108           6.7          2.5           5.8          1.8   virginica
50            7.0          3.2           4.7          1.4  versicolor
33            5.5          4.2           1.4          0.2      setosa
25            5.0          3.0           1.6          0.2      setosa

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(iris_data.drop('species',axis=1),
                                               iris_data['species'],test_size=0.2,random_state=100)

In [6]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [14]:
from sklearn.decomposition import PCA
pca=PCA()
X_train=pca.fit_transform(X_train)
X_test=pca.transform(X_test)

In [15]:
explained_variance=pca.explained_variance_
explained_variance

array([2.88152468, 0.97470924, 0.15721585, 0.02016367])

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(iris_data.drop('species',axis=1),
                                               iris_data['species'],test_size=0.2,random_state=100)
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)
from sklearn.decomposition import PCA
pca=PCA(n_components=1)
X_train=pca.fit_transform(X_train)
X_test=pca.transform(X_test)
explained_variance=pca.explained_variance_
explained_variance

array([2.88152468])

In [18]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(max_depth=2,random_state=100,n_estimators=10)
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test)

In [20]:
from sklearn.metrics import confusion_matrix  
from sklearn.metrics import accuracy_score,classification_report
print(classification_report(y_pred,y_test))
cm = confusion_matrix(y_test, y_pred)  
print(cm)  
print('Accuracy ' ,  accuracy_score(y_test, y_pred))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        11
  versicolor       0.83      0.83      0.83         6
   virginica       0.92      0.92      0.92        13

    accuracy                           0.93        30
   macro avg       0.92      0.92      0.92        30
weighted avg       0.93      0.93      0.93        30

[[11  0  0]
 [ 0  5  1]
 [ 0  1 12]]
Accuracy  0.9333333333333333


In [22]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(iris_data.drop('species',axis=1),
                                               iris_data['species'],test_size=0.2,random_state=100)
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)
from sklearn.decomposition import PCA
pca=PCA(n_components=2)
X_train=pca.fit_transform(X_train)
X_test=pca.transform(X_test)
explained_variance=pca.explained_variance_
print(explained_variance)
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(max_depth=2,random_state=100,n_estimators=10)
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test)
from sklearn.metrics import confusion_matrix  
from sklearn.metrics import accuracy_score,classification_report
print(classification_report(y_pred,y_test))
cm = confusion_matrix(y_test, y_pred)  
print(cm)  
print('Accuracy ' ,  accuracy_score(y_test, y_pred))

[2.88152468 0.97470924]
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        11
  versicolor       0.83      0.83      0.83         6
   virginica       0.92      0.92      0.92        13

    accuracy                           0.93        30
   macro avg       0.92      0.92      0.92        30
weighted avg       0.93      0.93      0.93        30

[[11  0  0]
 [ 0  5  1]
 [ 0  1 12]]
Accuracy  0.9333333333333333


In [23]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(iris_data.drop('species',axis=1),
                                               iris_data['species'],test_size=0.2,random_state=100)
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)
from sklearn.decomposition import PCA
pca=PCA(n_components=3)
X_train=pca.fit_transform(X_train)
X_test=pca.transform(X_test)
explained_variance=pca.explained_variance_
print(explained_variance)
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(max_depth=2,random_state=100,n_estimators=10)
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test)
from sklearn.metrics import confusion_matrix  
from sklearn.metrics import accuracy_score,classification_report
print(classification_report(y_pred,y_test))
cm = confusion_matrix(y_test, y_pred)  
print(cm)  
print('Accuracy ' ,  accuracy_score(y_test, y_pred))

[2.88152468 0.97470924 0.15721585]
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        11
  versicolor       0.83      0.62      0.71         8
   virginica       0.77      0.91      0.83        11

    accuracy                           0.87        30
   macro avg       0.87      0.84      0.85        30
weighted avg       0.87      0.87      0.86        30

[[11  0  0]
 [ 0  5  1]
 [ 0  3 10]]
Accuracy  0.8666666666666667


In [24]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(iris_data.drop('species',axis=1),
                                               iris_data['species'],test_size=0.2,random_state=100)
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)
from sklearn.decomposition import PCA
pca=PCA()
X_train=pca.fit_transform(X_train)
X_test=pca.transform(X_test)
explained_variance=pca.explained_variance_
print(explained_variance)
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(max_depth=2,random_state=100,n_estimators=10)
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test)
from sklearn.metrics import confusion_matrix  
from sklearn.metrics import accuracy_score,classification_report
print(classification_report(y_pred,y_test))
cm = confusion_matrix(y_test, y_pred)  
print(cm)  
print('Accuracy ' ,  accuracy_score(y_test, y_pred))

[2.88152468 0.97470924 0.15721585 0.02016367]
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        11
  versicolor       0.83      0.50      0.62        10
   virginica       0.62      0.89      0.73         9

    accuracy                           0.80        30
   macro avg       0.82      0.80      0.78        30
weighted avg       0.83      0.80      0.79        30

[[11  0  0]
 [ 0  5  1]
 [ 0  5  8]]
Accuracy  0.8
