In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
bankdata=pd.read_csv('bill_authentication.csv')

In [4]:
bankdata.sample(5)

Variance  Skewness  Curtosis   Entropy  Class
209     2.1721  -0.73874   5.46720 -0.723710      0
301     2.9719   6.83690  -0.27020  0.712910      0
1216    0.6005   0.99945  -2.21260  0.097399      1
1005   -2.8990  -0.60424   2.60450  1.377600      1
52      3.1452   5.82500  -0.51439 -1.494400      0

In [5]:
bankdata.isnull().sum()

Variance    0
Skewness    0
Curtosis    0
Entropy     0
Class       0
dtype: int64

In [6]:
bankdata.shape

(1372, 5)

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(bankdata.drop('Class',axis=1),
                                              bankdata['Class'],test_size=0.2,random_state=42)

In [8]:
from sklearn.svm import SVC
svclassifier=SVC(kernel='linear')
svclassifier.fit(X_train,y_train)
predict=svclassifier.predict(X_test)

In [11]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(predict,y_test))
print(confusion_matrix(predict,y_test))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       148
           1       0.98      0.98      0.98       127

    accuracy                           0.99       275
   macro avg       0.99      0.99      0.99       275
weighted avg       0.99      0.99      0.99       275

[[146   2]
 [  2 125]]


In [13]:
from sklearn import datasets
import seaborn as sns

In [14]:
irisdata=sns.load_dataset('iris')

In [15]:
irisdata.sample(5)

sepal_length  sepal_width  petal_length  petal_width     species
111           6.4          2.7           5.3          1.9   virginica
53            5.5          2.3           4.0          1.3  versicolor
49            5.0          3.3           1.4          0.2      setosa
139           6.9          3.1           5.4          2.1   virginica
135           7.7          3.0           6.1          2.3   virginica

In [17]:
from sklearn.model_selection import train_test_split  
X_train_2, X_test_2, y_train_2, y_test_2 = train_test_split(irisdata.drop('species',axis=1),irisdata['species'], test_size = 0.20, random_state=42)  

In [18]:
X_train_2.shape

(120, 4)

In [19]:
X_test_2.shape

(30, 4)

In [30]:
from sklearn.svm import SVC
sv=SVC(kernel='poly',degree=8,gamma='auto')
sv.fit(X_train_2,y_train_2)
predict_iris=sv.predict(X_test_2)

In [31]:
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test_2, predict_iris))  
print(classification_report(y_test_2, predict_iris))

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [32]:
from sklearn.model_selection import train_test_split  
X_train_2, X_test_2, y_train_2, y_test_2 = train_test_split(irisdata.drop('species',axis=1),irisdata['species'], test_size = 0.20, random_state=42) 
from sklearn.svm import SVC
sv=SVC(kernel='rbf',gamma='auto')
sv.fit(X_train_2,y_train_2)
predict_iris=sv.predict(X_test_2)

In [33]:
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test_2, predict_iris))  
print(classification_report(y_test_2, predict_iris))

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [34]:
from sklearn.model_selection import train_test_split  
X_train_2, X_test_2, y_train_2, y_test_2 = train_test_split(irisdata.drop('species',axis=1),irisdata['species'], test_size = 0.20, random_state=42) 
from sklearn.svm import SVC
sv=SVC(kernel='sigmoid',gamma='auto')
sv.fit(X_train_2,y_train_2)
predict_iris=sv.predict(X_test_2)
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test_2, predict_iris))  
print(classification_report(y_test_2, predict_iris))

[[ 0 10  0]
 [ 0  9  0]
 [ 0 11  0]]
              precision    recall  f1-score   support

      setosa       0.00      0.00      0.00        10
  versicolor       0.30      1.00      0.46         9
   virginica       0.00      0.00      0.00        11

    accuracy                           0.30        30
   macro avg       0.10      0.33      0.15        30
weighted avg       0.09      0.30      0.14        30



C:\anaconda\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\anaconda\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\anaconda\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
